
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    app: {{ template "fullname" . }}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-db
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: db
        image: {{ .Values.db.image }}
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-api
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}-api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 8080
          name: api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-web
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}-web
        image: {{ .Values.web.image }}
        ports:
        - containerPort: 80
          name: words-web
