apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ template "fullname" . }}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: {{ template "fullname" . }}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: Service
metadata:
  name: words
  labels:
    app: {{ template "fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: {{ template "fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-web 
  labels:
    app: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{default "80" .Values.web.servicePort }}
      targetPort: 80
      name: web
  selector:
    app: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
