apiVersion: v1
kind: ServiceAccount
metadata:
  name: superaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: superrole
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: superbinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: superaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: superrole
  apiGroup: rbac.authorization.k8s.io
