----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: private-registry
  labels:
    name: private-registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol-03"
