----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: private-registry
selector:
    name: private-registry
spec:
  accessModes:
  - ReadWriteOnce  
  resources:
    requests:
      storage: 10Gi