apiVersion: v1
kind: ReplicationController
metadata:
  name: private-registry
  labels:
    name: private-registry
spec:
  replicas: 1
  selector:
    name: private-registry
  template:
    metadata:
      labels:
        name: private-registry
    spec:
      containers:
      - name: private-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        imagePullPolicy: Always
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: 10.0.0.6
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000"
        ports:
        - name: www
          containerPort: 80
      - name: private-registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        env:
        - name: STORAGE_PATH
          value: /var/lib/registry
        - name: SEARCH_BACKEND
          value: sqlalchemy
        ports:
        - name: api
          containerPort: 5000

