apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-scala-builder
  labels:
    name: jenkins-scala-builder
spec:
  replicas: 1
  selector:
    name: jenkins-scala-builder
  template:
    metadata:
      labels:
        name: jenkins-scala-builder
    spec:
      containers:
      - name: jenkins-scala-slave
        image: akranga/jenkins-scala-builder
        imagePullPolicy: Always
        args: ["-name", "scala-slave", "-labels", "java scala sbt"]
        env:
        - name: SBT_OPTS
          value: "-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
        ports:
        - name: build-executor
          containerPort: 50000
        volumeMounts:
        - name: jenkins-workspace
          mountPath: /var/jenkins_home/workspace
        - name: build-cache1
          mountPath: /root/.sbt
        - name: build-cache2
          mountPath: /root/.ivy2
      volumes:
       - name: jenkins-workspace
         persistentVolumeClaim:
           claimName: jenkins-workspace
       - name: build-cache1
         hostPath:
           path: "/vol/data01"
       - name: build-cache2
         hostPath:
           path: "/vol/data02"
#       - name: build-cache1
#         persistentVolumeClaim:
#           claimName: build-cache1
#       - name: build-cache2
#         persistentVolumeClaim:
#           claimName: build-cache2
