apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - name: master
        image: akranga/jenkins
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: build-executor
          containerPort: 50000
        volumeMounts:
        - name: jenkins-workspace
          mountPath: /var/jenkins_home/workspace
          readOnly: false
        - name: jenkins-jobs
          mountPath: /var/jenkins_home/jobs
          readOnly: false
      volumes:
      - name: jenkins-jobs
        persistentVolumeClaim:
          claimName: jenkins-jobs
      - name: jenkins-workspace
        persistentVolumeClaim:
          claimName: jenkins-workspace