apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-java-slave
  labels:
    name: jenkins-java-slave
spec:
  replicas: 1
  selector:
    name: jenkins-java-slave
  template:
    metadata:
      labels:
        name: jenkins-java-slave
    spec:
      containers:
      - name: jenkins-java-slave
        image: akranga/jenkins-java-builder
        imagePullPolicy: Always
        args: ["-name", "java-slave", "-labels", "default java"]
        env:
        - name: JENKINS_HOME
          value: /var/jenkins_home
        ports:
        - name: build-executor
          containerPort: 50000
        volumeMounts:
        - name: jenkins-workspace
          mountPath: /var/jenkins_home/workspace
      volumes:
       - name: jenkins-workspace
         persistentVolumeClaim:
           claimName: jenkins-workspace
