apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  ports:
  - name: web
    port: 80
    targetPort: http
  - name: web8080
    port: 8080
  - name: swarm
    port: 50000
  selector:
    name: jenkins
