apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-vol1
  labels:
    name: jenkins-workspace
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol-01"
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-vol2
  labels:
    name: jenkins-jobs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol-02"