---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rollout
  namespace: rollout
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-ro
  namespace: rollout
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "pods/attach"]
  verbs: ["options"]
- apiGroups: [""]
  resources: ["pods/proxy", "services/proxy"]
  verbs: ["options"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets", "nodes", "namespaces", "configmaps"]
  verbs: ["options"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout
  namespace: rollout
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-ro
subjects:
- kind: ServiceAccount
  name: rollout
  namespace: rollout