apiVersion: v1
kind: ReplicationController
metadata:
  name: chuck
  labels:
    name: chucknorris
spec:
  replicas: 1
  selector:
    app: chuck
    version: 0.1.0
  template:
    metadata:
      labels:
        app: chuck
        version: 0.1.0
    spec:
      containers:
      - name: chuck
        image: akranga/chucknorris
        imagePullPolicy: Never
        ports:
        - name: api
          containerPort: 8080