apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuck-deployment
spec:
  selector:
    matchLabels:
      app: chuck
  replicas: 2
  template:
    metadata:
      labels:
        app: chuck
    spec:
      containers:
      - name: chuck
        image: akranga/chucknorris:latest
        ports:
        - containerPort: 8080
